
build:
  version : "1.0"
accounts:
  message: "Welcome to Eazybank accounts related Prod APIs"
  contactDetails:
    name: "ASD-Production Developer"
    email: "PROD@example.com"
  onCallSupport:
      - (555)555-1234
      - (555)555-1234