
build:
  version : "2.0"
accounts:
  message: "Welcome to Eazybank accounts related QA APIs"
  contactDetails:
    name: "QA-Developer"
    email: "QA@example.com"
  onCallSupport:
      - (555)555-1234
      - (555)555-1234