spring:
  application:
    name: "configserver"
  profiles:
    #    active: native
    ##    native=> used only when you are giving the search-location inside the classpath or file system
    active: git
    ## git=> given when you want configuration files from github

  cloud:
    config:
      server:
#        native:
#          search-location: "file:///C://Web Development//Microservices//Giving_configurations_using_classpath"
##          search-location: "classpath:/config"
###           Here "config"=> name of the folder where the application.yml are stored of microservices

        git:
          uri: "https://github.com/BhargavNikumbh/microservices-tutorial-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "!24252@#^@^&$*@#E"
server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true